# Generated by Django 6.0.1 on 2026-01-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('theory', models.TextField(verbose_name='Теория')),
                ('video_url', models.URLField(verbose_name='Видео (YouTube)')),
                ('subject', models.CharField(default='Математика', max_length=50, verbose_name='Предмет')),
                ('grade', models.IntegerField(default=9, verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date', models.CharField(max_length=100, verbose_name='Дата')),
                ('location', models.CharField(max_length=255, verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('feed', 'Лента'), ('news', 'Новости'), ('poll', 'Опрос')], max_length=10, verbose_name='Тип')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.TextField(max_length=280, verbose_name='Текст')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Картинка')),
                ('poll_results', models.JSONField(blank=True, null=True, verbose_name='Результаты опроса')),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('avatar_url', models.CharField(max_length=255, verbose_name='URL Аватара')),
                ('interests', models.JSONField(default=list, verbose_name='Интересы')),
                ('xp', models.IntegerField(default=50, verbose_name='Очки опыта')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('is_founder', models.BooleanField(default=True, verbose_name='Статус Основателя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
