# Generated by Django 5.2.10 on 2026-02-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatroom_studentquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='educationtestquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={},
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тег'),
        ),
    ]
